features.js
changes the definitions of gatheredHost and gatheredStun
to return undefined if there are no onicecandidate events.
=> feature: change gatheredhost / gatheredstun definition

Dockerfile
This fixes the issue that prevented downloading the maxmind database
=> Docker: Run npm install as the app user

extract.js
since in the change to copy args in
https://github.com/opentok/rtcstats/pull/33
the serialized argument is an array, not an object.
(internally some stuff like the metadata is still an object though)
=> extract: data.time is not a thing

features.js
i have seen quite some instances of sessionDuration
being negative due to timestamps switching from 2017 to 1980.
This guards against this.
```
["getstats","PC_0",{"ssrc_495244175_recv":{"googDecodingCTN":"102668","packetsReceived":"51210","googPreferredJitterBufferMs":"140","googDecodingNormal":"101099","googAccelerateRate":"0.00744629","bytesReceived":"1194406","googCurrentDelayMs":"273","googCaptureStartNtpTimeMs":"3703941555357","googJitterBufferMs":"195"},"ssrc_3094228494_recv":{"googCaptureStartNtpTimeMs":"3703941555590","googTargetDelayMs":"183","packetsReceived":"58349","googFrameRateReceived":"5","qpSum":"105900","framesDecoded":"6268","bytesReceived":"64346755","googCurrentDelayMs":"135","googMinPlayoutDelayMs":"183","googJitterBufferMs":"96"},"bweforvideo":{"googActualEncBitrate …
```
=> feature: ensure sessionduration > 0

features.js, getstats-mangle.js
instead of candidatepair. Firefox 53 changed the native stat type.
(and chrome still uses legacy stats)
=> stats: look for candidate-pair

features.js
'cause VPN... in particular this:
{"id":"Cand-/MldeHxA","timestamp":1537546468878,"type":"localcandidate","portNumber":"59322",
"networkType":"vpn",
"ipAddress":"y.y.y.x","transport":"udp","candidateType":"peerreflexive","priority":"1853759231"}
=> feature: add local network type to firstcandidatepair

features.js
which bailed out on the null candidate instead of break-ing
=> fix numberofinterfaces feature

obfuscator.js
fixes a bug which caused candidates in sdp to have lines starting with "candidate:" instead of "a=candidate:"
=> obfuscator: don't break candidates in sdp

test/client.js
which bailed out due to the old test client sending an old data format missing timestamps.
Now it bails out trying to upload data
=> partially fix `npm test`

features.js, utils.js
working towards #56 this makes extractTrack use a function extractTracks which returns a map of all tracks.
Bonus: fixes missing support for addStream for legacy apps still using that function.
Test Plan:
- test old and new version with different dumps, should be (nearly) identical
=> refactor extractTrack

extract.js, features-stream.js
defined by an increase in bytesReceived/bytes.
This doesn't work with unified plan because of
https://bugs.chromium.org/p/chromium/issues/detail?id=943493
which breaks our correlation between stats and ontrack
=> add feature measuring how long a track is actively sending or receiving data

obfuscator.js
this was broken due to the update to sdp 2.x which parses and prefers .address instead of .ip
=> obfuscate candidate ips again

extract.js
otherwise GUM errors without peerconnections will never show up
=> handle gum-only connections again

extract.js
ref #279
do not convert booleans to 0/1. This was done for redshift but breaks bigquery when trying to load files.
=> extract: dont convert bool to 0/1

app.js, store/s3.js
Moves the file reading to the s3 storage object since the GCP bucket API can only upload
based on local filename, not (easily) string contents
=> move file reading to s3 storage object

config/default.yaml, config/production.yaml, package.json, store/gcp.js
Ref #279
adds support for uploading to a GCP bucket instead of S3.
GCP automatically supports  gzip-ing. This was tested similar to #296
by uploading a single-byte file which results in a 22 byte gzip file in storage.
=> add support for uploading to gcp

extract.js, features-connection.js
if its not possible to pass extra things to the peerconnection constructor provide
a fallback way to set the client and conference ids. The rtcstats trace looks like this:
['identity', null, {user: 'something', conference: 'firechat'}]
where `user` is the same thing passed as rtcStatsClientIdentifier and `conference`
is the same thing passed as rtcStatsConferenceIdentifier in the non-fallback case.
=> add fallback identity information

app.js, config/default.yaml, config/production.yaml
Depending on your deployment, it may happen that the Load Balancer is including itself in the `X-Forwarded-For` header (e.g. in GCP)
We're giving the option to skip the last IP added to the header (false by default).
=> Skip last IP in X-Forwarded-For header

database/redshift-firehose.js
When Kinesis is not able to accept more records because of throtelling we generate many errors with very verbose and useless information.
=> Make firehose failures logging less noisy but higher level

artillery.config
I just used artillery for a simple load testing of rtcstats servers.    
It can be run with: 
`artillery run artillery.config` 
And we could add more complex scenarios with real rtcstats data.
Hope it helps somebody else.
=> Add basic artillery config file

app.js
When 'error' event is not catched it will stop the process.   This is happening in production some times with invalid websocket frames:  `Invalid WebSocket frame: RSV1 must be clear`
Test Plan:
- No known way to test it but at least test still works after this change.
=> Add listener for websockets error events

features-connection.js
which is negated, there is a failure if ice connected but dtls never did
=> fix dtlsFailure flag

features-connection.js
in order to tag connections which utilize p2p as an alternative to a 1:1-sfu
clients need to set the optional rtcStatsSFUP2P constraint to true when using those
=> add sfup2p feature

config/default.yaml, config/production.yaml, database/bigquery.js
more closely matching redshift behaviour. config.fields was introduced
to solve the same problem but this solution is better
fixes #326
=> bigquery: ignore unknown values during import, remove config.fields
