features.js
features.sql

should be using uuids but I need to track down something I suspect
about the bucket delay issue.

feature: remote stream id and track ids

---

features.js
features.sql

@ggarber any better ideas on doing this?

feature: detect simulcast

---

features.js

when using this in M65 it will not extract tracks
that are added using the native addTrack

features: fix track extraction for addTrack

---

config/default.yaml
config/production.yaml
database.js
extract.js

not using it anymore, the firehose stuff is much more powerful
@ggarber not sure why I can not request a review from you... please do anyway :)

remove dynamodb

---

app.js

otherwise its hard to find out the clientid

app: add more logging

---

database.js

why was there no linting process to prevent this :-/

fix errors

---

app.js
database.js
extract.js
features.js
fetchdump.js
getstats-deltacompression.js
getstats-mangle.js
obfuscator.js
store.js

use codemods to modernize code a bit

---

app.js
extract.js

this allows things like batching requests more easily

move responsibility for database write to main process

---

features.js

negative lifetime should not happen but somehow does. Ignore that..

feature: positive lifetime

---

features.js

as described in https://groups.google.com/forum/?utm_medium=email&utm_source=footer#!msg/discuss-webrtc/fYw3aNF7W78/ATppWHLNAQAJ

feature: add aec3 gum constraint

---

features.js

not just onaddstream which is missing in M70 with unified plan
Fixes #238

features: make extractTrack work on ontrack

---

features.js

extractTrack was extracting the wrong track. Broken in #239

features: fix for regression in extractTrack

---

features.js
getstats-mangle.js
obfuscator.js

changes shipped in Chrome 71, mediaType should be removed at some point.
Prefer kind everywhere

mediaType was renamed to kind

---

queries/README.md
queries/lib/graph.js
queries/lib/query.js
queries/queries.js

adds a bunch of common queries that describe the overall behaviour of a platform
@argggh as discussed, can you sign this off please?

add example platform metric queries

---

getstats-mangle.js

dont mangle timestamp on stats

---

features.js
getstats-deltacompression.js

also fixes #235 (the receiving*10s feature)

restore timestamps in delta compression

---

features.js

adds a feature that counts the number of different remote streams over the peerconnections lifetime

feature: number of remote streams

---

extract.js
features-client.js
features-connection.js
features.js

into clientfeatures.js (only one argument) and connectionfeatures.js (two arguments)
Test Plan:
* run old and new code on sample input, ensure output is identical

split features.js

---

extract.js
features-client.js

see also https://github.com/opentok/rtcstats/pull/92

add websocket connection time

---

getstats-deltacompression.js

see https://github.com/opentok/rtcstats/issues/89 and corresponding commits.

decompress report.timestamp == 0

---

queries/queries.js

adds a query measuring the number of ice restarts

add ice restart query

---

Dockerfile
Makefile

Debian: 1.05 GB
Alpine:  231 MB

Prefer alpine instead of debian

---

app.js

- `https` not required
- changes to `setupWorkDirectory`
- slim `run` method by calling functions per each task/setup
- make sure `replace('OnError', ...` only replaces the last appearance

some changes to app.js

---

database.js
package.json

Removes lodash since ES6 makes this reasonably easy to do ourselves

remove lodash

---

database.js

follow-up on https://github.com/fippo/rtcstats-server/pull/283#pullrequestreview-323325436
Tested with sample dump and checked that this makes no difference in the output

use Object.assign instead of iterating over keys

---

features-client.js

otherwise this will be coerced from false to '0'
SQL changes:
alter table features set getusermediaerror = null where getusermediaerror = '0'

getusermediaerror: return undefined on no error

---

.travis.yml
app.js
store/s3.js

This reverts commit 493457cd047ee981a3ddabf8bcb47fd8dd841f7c.
and re-adds travis support

Revert "remove travis integration"

---

store/s3.js

allow manual testing by using
node store/s3 <bucketname> <filename>
since that turned out to be an issue in #294

s3: allow easy testing

---

database/bigquery.js
package.json

ref #279 
adds support for bigquery by using load to (occasionally) import files into the database.
There is a whitelist of fields as bigquery does not ignore unkonwn entries.

add bigquery support

---

app.js
config/default.yaml
config/production.yaml
database/bigquery.js

or hybrid modes like using aws s3 for storage and bigquery for sql

allow using gcp instead of aws

---

app.js
config/default.yaml
extract.js
features-client.js
features-connection.js
features-v2.sql
package.json

fixes #286 and #300. Maxmind is removed, it is more useful to query in any frontend anyway.
The location is replaced by the redefined publicIPAddress feature (which was previously based
on the clients ICE ip but now comes from the IP connecting to the rtcstats-server.

remove maxmind + port publicIP/useshttpproxy

---

Makefile
database/bigquery.js
package.json
store/gcp.js
store/s3.js

Also fixing an issue while trying to upload a file to GCP storage

make target to run with nodemon

---

.eslintrc
.gitignore
Makefile
app.js
config/default.yaml
config/production.yaml
database/bigquery.js
database/redshift-firehose.js
logging.js
package-lock.json
package.json
store/gcp.js

`appender` configuration was not used (unless I missed something 😊 ).
Adding `winston` as logging library, which will help to format based on the client requirements.
Also log to STDOUT to keep progressing on becoming a [12 factor app 😆 ](https://12factor.net/logs)

Add winston library + configure eslint with airbnb base rules

---

.eslintrc
app.js
database/redshift-firehose.js
extract.js
features-connection.js
features-stream.js
getstats-mangle.js
store/gcp.js
store/s3.js

make eslint actually do something

---

obfuscator.js

add missing 'publicIP' handling to obfuscator

---

features-connection.js

which was assumed to be an array but it should have been an object

fix getPeerConnectionConstraints default value

---

features-connection.js

Add check for defined peerConnectionConfig before accessing its browserType property
